
```{r}
library(ggplot2)
library(gganimate)
library(dplyr)
library(ggpattern)

source("parse_utils.R")

location = "lismore" 

name_mapping <- c(
  "lismore" = "Lismore",
  "perth" = "Perth",
  "tennant" = "Tennant Creek"
)
mapped_location <- name_mapping[location]

data <- process_data_LP(location)

df <- data %>%
    mutate(Avg_Temp = (T.Max + T.Min) / 2) %>%
    group_by(Year = format(Date, "%Y")) %>%
    summarise(
      Avg_Temp = mean(Avg_Temp, na.rm = TRUE)
    )

df <- df %>%
  mutate(Year = as.Date(paste0(Year, "-01-01"), format = "%Y-%m-%d"))

df
```

```{r}
reference_period <- df %>%
  filter(Year >= as.Date("1995-01-01") & Year <= as.Date("2014-01-01")) %>%
  summarise(Reference_Avg = mean(Avg_Temp, na.rm = TRUE)) %>%
  pull(Reference_Avg)

reference_period
```


```{r}
projections <- data.frame(
  Scenario = c(rep("SSP1-1.9", 4), rep("SSP1-2.6", 4), rep("SSP2-4.5", 4), rep("SSP3-7.0", 4), rep("SSP5-8.5", 4)),
  Year = as.Date(c(
    "2014-01-01", "2040-01-01", "2060-01-01", "2100-01-01", 
    "2014-01-01", "2040-01-01", "2060-01-01", "2100-01-01", 
    "2014-01-01", "2040-01-01", "2060-01-01", "2100-01-01", 
    "2014-01-01", "2040-01-01", "2060-01-01", "2100-01-01", 
    "2014-01-01", "2040-01-01", "2060-01-01", "2100-01-01"
  )),
  Best_Estimate = c(0, 0.65, 0.75, 0.55, 0, 0.65, 0.85, 0.95, 0, 0.65, 1.15, 1.85, 0, 0.65, 1.25, 2.75, 0, 0.75, 1.55, 3.55) + reference_period,
  Low_Range = c(0,0.35, 0.35, 0.15, 0, 0.35, 0.45, 0.45, 0, 0.35, 0.75, 1.25, 0, 0.35, 0.85, 1.95, 0, 0.45, 1.05, 2.45) + reference_period,
  High_Range = c(0, 0.85, 1.15, 0.95, 0, 0.95, 1.35, 1.55, 0, 0.95, 1.65, 2.65, 0, 0.95, 1.75, 3.75, 0, 1.05, 2.15, 4.85) + reference_period
)

projections
```

```{r}
ggplot(df, aes(x = Year, y = Avg_Temp)) +
  geom_line(color = "blue", size = 1) +
  labs(
    title = paste(mapped_location, "- Average Temperature"),
    x = "Year",
    y = "Average Temperature (°C)"
  ) +
  theme_minimal()
```
```{r}
ggsave(filename = paste0("climate_temp_projections_", location, "1.png"),width = 10,height = 6)
```

```{r}
# Plot historical data and future projections
ggplot(df, aes(x = Year, y = Avg_Temp)) +
  geom_line(color = "blue", size = 1) +
  labs(
    title = paste(mapped_location, "- Average Temperature Projections"),
    x = "Year",
    y = "Average Temperature (°C)"
  ) +
  theme_minimal() +
  
  # projection lines for best estimates
  geom_line(data = projections, aes(x = Year, y = Best_Estimate, color = Scenario), size = 1.2, linetype = "dashed") +
  
  scale_color_manual(values = c("SSP1-1.9" = "green", "SSP1-2.6" = "orange", "SSP2-4.5" = "blue", "SSP3-7.0" = "red", "SSP5-8.5" = "purple")) +
  scale_fill_manual(values = c("SSP1-1.9" = "green", "SSP1-2.6" = "orange", "SSP2-4.5" = "blue", "SSP3-7.0" = "red", "SSP5-8.5" = "purple")) +
  theme(legend.position = "right")
```
```{r}
ggsave(filename = paste0("climate_temp_projections_", location, "2.png"),width = 10,height = 6)
```


```{r}
p <- ggplot() +
  geom_line(data = df, aes(x = Year, y = Avg_Temp), color = "blue", size = 1) +
  labs(
    title = paste(mapped_location, "- Average Temperature Senario Projections"),
    x = "Year",
    y = "Average Temperature (°C)"
  ) +
  theme_minimal()

# Check if projections data is available and has necessary columns
if (exists("projections") && all(c("Year", "Low_Range", "High_Range", "Best_Estimate", "Scenario") %in% colnames(projections))) {
  p <- p + geom_line(data = projections, aes(x = Year, y = Best_Estimate, color = Scenario), size = 1.2, linetype = "dashed") +
    
    # Shaded region for very likely range
    geom_ribbon(data = projections, aes(x = Year, ymin = Low_Range, ymax = High_Range, fill = Scenario), alpha = 0.2)
}
p <- p + 
  scale_color_manual(values = c("SSP1-1.9" = "green", 
                                 "SSP1-2.6" = "orange", 
                                 "SSP2-4.5" = "blue", 
                                 "SSP3-7.0" = "red", 
                                 "SSP5-8.5" = "purple")) +
  scale_fill_manual(values = c("SSP1-1.9" = "green", 
                                "SSP1-2.6" = "orange", 
                                "SSP2-4.5" = "blue", 
                                "SSP3-7.0" = "red", 
                                "SSP5-8.5" = "purple")) +
  theme(legend.position = "right")

print(p)

```
```{r}
ggsave(filename = paste0("climate_temp_projections_", location, "3.png"),
       plot = p,
       width = 10,
       height = 6)
```

